### ISSUE TITLE
Game goal/points - Feature Request

### ISSUE THREAD

**Issue by elisabeth-h7** [info442-su23/h-team#50]
I think it would be interesting to have some sort of point system or a goal to reach for the game. By adding this, users would be more engaged and encouraged to keep playing until they reached the goal.

**Comment by vuongb2** [comment]
Hi Elisabeth, thank you for this feature request. This is a great idea and is something that could increase engagement and motivation for people to use our product. This will be done in a future sprint as we user test, research, and even ideate better solutions, since we don't necessarily have a valid goal. Since we plan on increasing the size of our database to include hundreds of items, it doesn't make sense to have a progress bar for the entire database. But if our progress tracker is for less items, it makes sense to include a reward for completing the task.

**Comment by atimch** [comment]
Implemented with Score branch push

**Comment by atimch** [comment]
score branch:
https://github.com/info442-su23/h-team/activity?ref=score
