### ISSUE TITLE
Randomize the Order of Items To Make the Game More Fun (Feature request)

### ISSUE THREAD

**Issue by DongTianjia** [info442-su23/h-team#51]
Every time I open up the game, identical items are generated for me in the same order. Randomize the order of the items so that the player is not starting with the same list of items like bread, cardboard..., etc for every game would make the player want to come back playing the game more.

**Comment by vuongb2** [comment]
This is a valid feature request that we will try to develop in a future sprint. Currently, our database does not justify adding a random order yet because it is so small, but as we expand and increase our database of game items it will make more sense to randomize the order of objects and even implement code to make sure objects aren't repeated.

**Comment by atimch** [comment]
branch AT#51: https://github.com/info442-su23/h-team/activity?ref=AT%2351
